music_directory    "~/Documents/123/music/"
playlist_directory "~/.config/mpd/playlists"
db_file            "~/.config/mpd/database"
log_file           "~/.config/mpd/log"
#for brew services
#pid_file           "~/.config/mpd/pid"
state_file         "~/.config/mpd/state"
follow_outside_symlinks "yes"
follow_inside_symlinks  "yes"
audio_output {
        type            "osx"
        name            "CoreAudio"
        mixer_type      "software" # Adds a separate volume slider for MPD
}
